version: '3'

services:
  web:
    environment:
      - PORT=8080
      - MONGODB=db
    build: ./cmd/currency
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: "mongo:latest"
    volumes:
      - db-data:/data/db

volumes:
  db-data:
